import { Bai_Jamjuree } from "next/font/google";
import "./globals.css";

const BaiJamjuree = Bai_Jamjuree({
	variable: "--font-bai-jamjuree",
	subsets: ["latin"],
	weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata = {
	title: "DaruGaming",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${BaiJamjuree.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
